import Head from "next/head";
import styles from "../styles/Home.module.css";
import ManualHeader from "../components/ManualHeader";
import Header from "../components/Header";

import LotterEntrace from "../components/LotteryEntrace";

import { useMoralis } from "react-moralis";

const supportedChains = ["31337", "5"];

export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis();

  return (
    <div className={styles.container}>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     {/*<ManualHeader />*/} 

      <br/>
      <br/>
      <br/>
      <Header/>
      <LotterEntrace></LotterEntrace>
    </div>
  );
}
